# Generated by Django 3.2.16 on 2025-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
